package com.view;

import com.koneksi.userid;
import com.model.model_disposisi;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FrmDisposisi extends javax.swing.JFrame {

    model_disposisi model = new model_disposisi();
    public FrmDisposisi() {
        initComponents();
        setLocationRelativeTo(this);
        txtBidang.setEnabled(false);
        txtBidang.setText(userid.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSuratdari = new javax.swing.JTextField();
        txtBidang = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIsidspsisi = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPerihal = new javax.swing.JTextArea();
        btnTampil = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUlang = new javax.swing.JButton();
        btnFilepdf = new javax.swing.JButton();
        cbTanggaltrm = new com.toedter.calendar.JDateChooser();
        cbTanggalhrini = new com.toedter.calendar.JDateChooser();
        ckParaf = new javax.swing.JCheckBox();
        lblFile = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rdk3 = new javax.swing.JRadioButton();
        rdKb = new javax.swing.JRadioButton();
        rdPp = new javax.swing.JRadioButton();
        rdKlbg = new javax.swing.JRadioButton();
        rdFslts = new javax.swing.JRadioButton();
        rdSekretaris = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        txtNmrSrt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNmrAgenda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtSuratdari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 240, -1));

        txtBidang.setEnabled(false);
        getContentPane().add(txtBidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 240, -1));

        txtIsidspsisi.setColumns(20);
        txtIsidspsisi.setRows(5);
        jScrollPane2.setViewportView(txtIsidspsisi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 240, 160));

        txtPerihal.setColumns(20);
        txtPerihal.setRows(5);
        jScrollPane1.setViewportView(txtPerihal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 160));

        btnTampil.setText("TAMPILKAN DATA");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });
        getContentPane().add(btnTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 130, 60));

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 130, 60));

        btnUlang.setText("ULANG");
        btnUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlangActionPerformed(evt);
            }
        });
        getContentPane().add(btnUlang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 130, 60));

        btnFilepdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        btnFilepdf.setText("unggah pdf");
        btnFilepdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilepdfActionPerformed(evt);
            }
        });
        getContentPane().add(btnFilepdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 190, 50));

        cbTanggaltrm.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(cbTanggaltrm, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 240, -1));

        cbTanggalhrini.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(cbTanggalhrini, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 240, -1));

        ckParaf.setText("Paraf");
        getContentPane().add(ckParaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        lblFile.setText("Silahkan pilih file");
        getContentPane().add(lblFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 250, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel6.setText("PERIHAL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setText("SURAT DARI");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel8.setText("DITERIMA TANGGAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel9.setText("<html>\n<body>\nMENGETAHUI<br>\nKEPALA DINAS\n</body>\n</html>");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel10.setText("TANGGAL");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel11.setText("ISI DISPOSISI");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("PROVINSI SULAWESI SELATAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("DINAS KEPENDUDUKAN, PENCATATAN SIPIL, PENGENDALIAN PENDUDUK DAN KELUARGA BERENCANA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setText("DISPOSISI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel15.setText("BIDANG");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel14.setText("DITERUSKAN KEPADA");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        rdk3.setText("KABID. KETAHANAN & KESEJAHTERAAN KELUARGA");
        getContentPane().add(rdk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        rdKb.setText("KABID. KELUARGA BERENCANA");
        getContentPane().add(rdKb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        rdPp.setText("KABID. PENGENDALIAN PENDUDUK");
        getContentPane().add(rdPp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        rdKlbg.setText("KABID. KELEMBAGAAN & INFORMASI ADMINDUK");
        getContentPane().add(rdKlbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        rdFslts.setText("KABID. FASILITASI  DAFDUK & CAPIL");
        getContentPane().add(rdFslts, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        rdSekretaris.setText("SEKRETARIS");
        getContentPane().add(rdSekretaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, -1, 60));
        getContentPane().add(txtNmrSrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 240, -1));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel13.setText("NOMOR SURAT");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));
        getContentPane().add(txtNmrAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 240, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel12.setText("NOMOR AGENDA");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlangActionPerformed
        try {
            model.Ulang(this);
        } catch (SQLException ex) {
            Logger.getLogger(FrmDisposisi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUlangActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            model.Simpan(this);
        } catch (SQLException ex) {
            Logger.getLogger(FrmDisposisi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        try {
            new FrmTplDsp().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmDisposisi.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnFilepdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilepdfActionPerformed
        try {
            model.Filepdf(this);
        } catch (SQLException ex) {
            Logger.getLogger(FrmDisposisi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFilepdfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FrmInput().show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilepdf;
    public javax.swing.JButton btnSimpan;
    public javax.swing.JButton btnTampil;
    public javax.swing.JButton btnUlang;
    public com.toedter.calendar.JDateChooser cbTanggalhrini;
    public com.toedter.calendar.JDateChooser cbTanggaltrm;
    public javax.swing.JCheckBox ckParaf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblFile;
    public javax.swing.JRadioButton rdFslts;
    public javax.swing.JRadioButton rdKb;
    public javax.swing.JRadioButton rdKlbg;
    public javax.swing.JRadioButton rdPp;
    public javax.swing.JRadioButton rdSekretaris;
    public javax.swing.JRadioButton rdk3;
    public javax.swing.JTextField txtBidang;
    public javax.swing.JTextArea txtIsidspsisi;
    public javax.swing.JTextField txtNmrAgenda;
    public javax.swing.JTextField txtNmrSrt;
    public javax.swing.JTextArea txtPerihal;
    public javax.swing.JTextField txtSuratdari;
    // End of variables declaration//GEN-END:variables
}
