/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.koneksi.userid;
import com.model.model_input;
import com.model.model_surat_keluar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class FrmSuratKeluar extends javax.swing.JFrame {

    model_surat_keluar model = new model_surat_keluar();
    public FrmSuratKeluar() {
        initComponents();
        setLocationRelativeTo(this);
        txtBidang.setEnabled(false);
        txtBidang.setText(userid.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNmrAgenda = new javax.swing.JTextField();
        txtLampiran = new javax.swing.JTextField();
        txtBidang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPerihal = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnUlang = new javax.swing.JButton();
        btnFilepdf = new javax.swing.JButton();
        btnTampil1 = new javax.swing.JButton();
        cbTanggal = new com.toedter.calendar.JDateChooser();
        lblFile = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTujuanSurat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNomorSurat = new javax.swing.JTextField();
        btnTampil2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNmrAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 240, -1));
        getContentPane().add(txtLampiran, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 240, -1));

        txtBidang.setEnabled(false);
        getContentPane().add(txtBidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 240, -1));

        txtPerihal.setColumns(20);
        txtPerihal.setRows(5);
        jScrollPane1.setViewportView(txtPerihal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 240, 110));

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 130, 60));

        btnUlang.setText("ULANG");
        btnUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlangActionPerformed(evt);
            }
        });
        getContentPane().add(btnUlang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 130, 60));

        btnFilepdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        btnFilepdf.setText("unggah pdf");
        btnFilepdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilepdfActionPerformed(evt);
            }
        });
        getContentPane().add(btnFilepdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 190, 50));

        btnTampil1.setText("MENU");
        btnTampil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampil1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTampil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 130, 60));

        cbTanggal.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(cbTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 240, -1));

        lblFile.setText("Silahkan pilih file");
        getContentPane().add(lblFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 250, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel6.setText("PERIHAL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setText("NOMOR AGENDA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel8.setText("TUJUAN SURAT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel9.setText("BIDANG");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel10.setText("TANGGAL DIBUAT");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel11.setText("LAMPIRAN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("PROVINSI SULAWESI SELATAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("DINAS KEPENDUDUKAN, PENCATATAN SIPIL, PENGENDALIAN PENDUDUK DAN KELUARGA BERENCANA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setText("INPUT DATA SURAT KELUAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(txtTujuanSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 240, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel12.setText("NOMOR SURAT");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        getContentPane().add(txtNomorSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 240, -1));

        btnTampil2.setText("TAMPILKAN DATA");
        btnTampil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampil2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTampil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 130, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlangActionPerformed
        try {
            model.Ulang(this);
        } catch (SQLException ex) {
            Logger.getLogger(FrmSuratKeluar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUlangActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            model.Simpan(this);
        } catch (SQLException ex) {
            Logger.getLogger(FrmSuratKeluar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnFilepdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilepdfActionPerformed
        try {
            model.UploadFile(this);
        } catch (SQLException ex) {
            Logger.getLogger(FrmSuratKeluar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFilepdfActionPerformed

    private void btnTampil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampil1ActionPerformed
        new FrmMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTampil1ActionPerformed

    private void btnTampil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampil2ActionPerformed
        try {
            new FrmTampilSuratKeluar().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmSuratKeluar.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnTampil2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilepdf;
    public javax.swing.JButton btnSimpan;
    public javax.swing.JButton btnTampil1;
    public javax.swing.JButton btnTampil2;
    public javax.swing.JButton btnUlang;
    public com.toedter.calendar.JDateChooser cbTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblFile;
    public javax.swing.JTextField txtBidang;
    public javax.swing.JTextField txtLampiran;
    public javax.swing.JTextField txtNmrAgenda;
    public javax.swing.JTextField txtNomorSurat;
    public javax.swing.JTextArea txtPerihal;
    public javax.swing.JTextField txtTujuanSurat;
    // End of variables declaration//GEN-END:variables
}
